Use generics for AppStoreConnectClient implementation
I want to use a trait for the connect_token: ConnectTokenEncoder member
instead of hardcoding its type so that we can obtain the token through
different means.
This seems easier said than done…
After reading
https://users.rust-lang.org/t/how-to-store-a-trait-as-field-of-a-struct/
I tried to go with the "generics" approach, but I’m not sure this will
be as convenient as I hope…

After adding generics up to the top level CLI objects, this looks like a
dead end as I need to return a concrete type, not a trait from
apple-codesign/src/cli/mod.rs, while my goal is to use different types
in the struct depending on the params.

warning: unused import: `ConnectTokenEncoder`
  --> apple-codesign/src/cli/mod.rs:11:25
   |
11 | use app_store_connect::{ConnectTokenEncoder, TokenGenerator};
   |                         ^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0782]: expected a type, found a trait
   --> apple-codesign/src/cli/mod.rs:143:45
    |
143 |     fn notarizer(&self) -> Result<Notarizer<TokenGenerator>, AppleCodesignError> {
    |                                             ^^^^^^^^^^^^^^
    |
help: you can add the `dyn` keyword if you want a trait object
    |
143 |     fn notarizer(&self) -> Result<Notarizer<dyn TokenGenerator>, AppleCodesignError> {
    |                                             +++

For more information about this error, try `rustc --explain E0782`.
warning: `apple-codesign` (lib) generated 1 warning
error: could not compile `apple-codesign` (lib) due to 1 previous error; 1 warning emitted